print("LHIEIEUESSCEPWMNDLAO"== "LHIEEIUESSCEPWMNDLAO")
print("LHIEEIUESSCEPMNWDLAO"== "LHIEEIUESSCEPWMNDLAO")
print("LHIEEIUESSCEPWMNDLOA"== "LHIEEIUESSCEPWMNDLAO")
print("LHIEEIUESSCEPWMNDLAO"== "LHIEEIUESSCEPWMNDLAO")